#include "opcode.h"

OpCodeHandler OpCodeTable[NB_OPCODES] =
{
    {"CMSG_HELLO",                          &FenPrincipale::handleHello},
    {"SMSG_HELLO",                          &FenPrincipale::handleServerSide},
    {"CMSG_AUTH_LOGIN",                     &FenPrincipale::handleAuthLogin},
    {"SMSG_AUTH_OK",                        &FenPrincipale::handleServerSide},
    {"SMSG_AUTH_INCORRECT_LOGIN",           &FenPrincipale::handleServerSide},
    {"SMSG_AUTH_ACCT_ALREADY_IN_USE",       &FenPrincipale::handleServerSide},
    {"SMSG_AUTH_IP_BANNED",                 &FenPrincipale::handleServerSide},
    {"SMSG_AUTH_ACCT_BANNED",               &FenPrincipale::handleServerSide},
    {"SMSG_AUTH_ERROR",                     &FenPrincipale::handleServerSide},
    {"CMSG_SET_NICK",                       &FenPrincipale::handleSetNick},
    {"SMSG_NICK_ALREADY_IN_USE",            &FenPrincipale::handleServerSide},
    {"SMSG_NICK_TOO_SHORT",                 &FenPrincipale::handleServerSide},
    {"SMSG_KICK",                           &FenPrincipale::handleServerSide},
    {"CMSG_CHAT_MESSAGE",                   &FenPrincipale::handleChatMessage},
    {"SMSG_CHAT_MESSAGE",                   &FenPrincipale::handleServerSide},
    {"SMSG_INVALID_MESSAGE",                &FenPrincipale::handleServerSide},
    {"SMSG_INVALID_NICK",                   &FenPrincipale::handleServerSide},
    {"SMSG_USER_JOINED",                    &FenPrincipale::handleServerSide},
    {"SMSG_USER_LEFT",                      &FenPrincipale::handleServerSide},
    {"SMSG_USER_RENAMED",                   &FenPrincipale::handleServerSide},
    {"SMSG_PING",                           &FenPrincipale::handleServerSide},
    {"CMSG_PONG",                           &FenPrincipale::handlePing},
    {"CMSG_REGISTER",                       &FenPrincipale::handleRegister},
    {"SMSG_REG_OK",                         &FenPrincipale::handleServerSide},
    {"SMSG_REG_ACCT_ALREADY_EXISTS",        &FenPrincipale::handleServerSide},
    {"SMSG_REG_INVALID_NICK",               &FenPrincipale::handleServerSide},
    {"SMSG_REG_ERROR",                      &FenPrincipale::handleServerSide},
    {"CMSG_KICK",                           &FenPrincipale::handleKick},
    {"CMSG_BAN",                            &FenPrincipale::handleBan},
    {"CMSG_VOICE",                          &FenPrincipale::handleVoice},
    {"CMSG_LVL_MOD",                        &FenPrincipale::handleLevelMod},
    {"SMSG_NOT_AUTHORIZED",                 &FenPrincipale::handleServerSide},
    {"SMSG_USER_DOESNT_EXIST",              &FenPrincipale::handleServerSide},
    {"SMSG_LVL_MOD_ERROR",                  &FenPrincipale::handleServerSide},
    {"SMSG_USER_KICKED",                    &FenPrincipale::handleServerSide},
    {"SMSG_USER_BANNED",                    &FenPrincipale::handleServerSide},
    {"SMSG_USER_VOICED",                    &FenPrincipale::handleServerSide},
    {"SMSG_LVL_MOD_OK",                     &FenPrincipale::handleServerSide},
    {"SMSG_LVL_MOD_INVALID_LEVEL",          &FenPrincipale::handleServerSide},
    {"SMSG_LVL_MOD_ACCT_DOESNT_EXIST",      &FenPrincipale::handleServerSide},
    {"SMSG_LVL_MOD_LEVEL_TOO_HIGH",         &FenPrincipale::handleServerSide},
    {"SMSG_LVL_MOD_NOT_YOURSELF",           &FenPrincipale::handleServerSide},
    {"SMSG_LVL_CHANGED",                    &FenPrincipale::handleServerSide},
    {"SMSG_NO_INTERACT_HIGHER_LEVEL",       &FenPrincipale::handleServerSide},

};
