#ifndef SHARED_H
#define SHARED_H

#define NB_OPCODES 0x33

enum OpCodeValues
{
    CMSG_HELLO                      = 0x00,
    SMSG_HELLO                      = 0x01,
    CMSG_AUTH_LOGIN                 = 0x02,        //acct_name, acct_pwhash, nick
    SMSG_AUTH_OK                    = 0x03,
    SMSG_AUTH_INCORRECT_LOGIN       = 0x04,
    SMSG_AUTH_ACCT_ALREADY_IN_USE   = 0x05,
    SMSG_AUTH_IP_BANNED             = 0x06,
    SMSG_AUTH_ACCT_BANNED           = 0x07,
    SMSG_AUTH_ERROR                 = 0x08,
    SMSG_AUTH_INCORRECT_VERSION     = 0x09,
    CMSG_SET_NICK                   = 0x0a,
    SMSG_NICK_ALREADY_IN_USE        = 0x0b,
    SMSG_NICK_TOO_SHORT             = 0x0c,
    SMSG_KICK                       = 0x0d,
    CMSG_CHAT_MESSAGE               = 0x0e,
    SMSG_CHAT_MESSAGE               = 0x0f,
    SMSG_INVALID_MESSAGE            = 0x10,
    SMSG_INVALID_NICK               = 0x11,
    SMSG_USER_JOINED                = 0x12,
    SMSG_USER_LEFT                  = 0x13,
    SMSG_USER_RENAMED               = 0x14,
    SMSG_PING                       = 0x15,
    CMSG_PONG                       = 0x16,
    CMSG_REGISTER                   = 0x17,
    SMSG_REG_OK                     = 0x18,
    SMSG_REG_ACCT_ALREADY_EXISTS    = 0x19,
    SMSG_REG_INVALID_NICK           = 0x1a,
    SMSG_REG_ERROR                  = 0x1b,
    CMSG_KICK                       = 0x1c,
    CMSG_BAN                        = 0x1d,
    CMSG_VOICE                      = 0x1e,
    CMSG_LVL_MOD                    = 0x1f,
    SMSG_NOT_AUTHORIZED             = 0x20,
    SMSG_USER_DOESNT_EXIST          = 0x21,
    SMSG_PROMOTE_ERROR              = 0x22,
    SMSG_USER_KICKED                = 0x23,
    SMSG_USER_BANNED                = 0x24,
    SMSG_USER_VOICED                = 0x25,
    SMSG_LVL_MOD_OK                 = 0x26,
    SMSG_LVL_MOD_INVALID_LEVEL      = 0x27,
    SMSG_LVL_MOD_ACCT_DOESNT_EXIST  = 0x28,
    SMSG_LVL_MOD_LEVEL_TOO_HIGH     = 0x29,
    SMSG_LVL_MOD_NOT_YOURSELF       = 0x2a,
    SMSG_LVL_CHANGED                = 0x2b,
    SMSG_NO_INTERACT_HIGHER_LEVEL   = 0x2c,
    CMSG_WHOIS                      = 0x2d,
    SMSG_WHOIS                      = 0x2e,
    CMSG_UPDATE_CLIENTS_LIST        = 0x2f,
    SMSG_CLIENTS_LIST               = 0x30,
    CMSG_LOGOUT                     = 0x31,
    CMSG_SET_LOGOUT_MSG             = 0x32,
};

#endif // SHARED_H
