#ifndef SHARED_H
#define SHARED_H

#define NB_OPCODES 0x44

enum OpCodeValues
{
    CMSG_HELLO                      = 0x00,
    SMSG_HELLO                      = 0x01,
    CMSG_AUTH_LOGIN                 = 0x02,        //acct_name, acct_pwhash, nick
    SMSG_AUTH_OK                    = 0x03,
    SMSG_AUTH_INCORRECT_LOGIN       = 0x04,
    SMSG_AUTH_ACCT_ALREADY_IN_USE   = 0x05,
    SMSG_AUTH_IP_BANNED             = 0x06,
    SMSG_AUTH_ACCT_BANNED           = 0x07,
    SMSG_AUTH_ERROR                 = 0x08,
    SMSG_AUTH_INCORRECT_VERSION     = 0x09,
    CMSG_SET_NICK                   = 0x0a,
    SMSG_NICK_ALREADY_IN_USE        = 0x0b,
    SMSG_NICK_TOO_SHORT             = 0x0c,
    SMSG_NICK_TOO_LONG              = 0x0d,
    SMSG_KICK                       = 0x0e,
    CMSG_CHAT_MESSAGE               = 0x0f,
    SMSG_CHAT_MESSAGE               = 0x10,
    SMSG_INVALID_MESSAGE            = 0x11,
    SMSG_INVALID_NICK               = 0x12,
    SMSG_USER_JOINED                = 0x13,
    SMSG_USER_LEFT                  = 0x14,
    SMSG_USER_RENAMED               = 0x15,
    SMSG_PING                       = 0x16,
    CMSG_PONG                       = 0x17,
    CMSG_REGISTER                   = 0x18,
    SMSG_REG_OK                     = 0x19,
    SMSG_REG_ACCT_ALREADY_EXISTS    = 0x1a,
    SMSG_REG_INVALID_NICK           = 0x1b,
    SMSG_REG_ERROR                  = 0x1c,
    CMSG_KICK                       = 0x1d,
    CMSG_BAN                        = 0x1e,
    CMSG_VOICE                      = 0x1f,
    CMSG_LVL_MOD                    = 0x20,
    SMSG_NOT_AUTHORIZED             = 0x21,
    SMSG_USER_DOESNT_EXIST          = 0x22,
    SMSG_PROMOTE_ERROR              = 0x23,
    SMSG_USER_KICKED                = 0x24,
    SMSG_USER_BANNED                = 0x25,
    SMSG_USER_VOICED                = 0x26,
    SMSG_LVL_MOD_OK                 = 0x27,
    SMSG_LVL_MOD_INVALID_LEVEL      = 0x28,
    SMSG_LVL_MOD_ACCT_DOESNT_EXIST  = 0x29,
    SMSG_LVL_MOD_LEVEL_TOO_HIGH     = 0x2a,
    SMSG_LVL_MOD_NOT_YOURSELF       = 0x2b,
    SMSG_LVL_CHANGED                = 0x2c,
    SMSG_NO_INTERACT_HIGHER_LEVEL   = 0x2d,
    CMSG_WHOIS                      = 0x2e,
    SMSG_WHOIS                      = 0x2f,
    CMSG_UPDATE_CLIENTS_LIST        = 0x30,
    SMSG_CLIENTS_LIST               = 0x31,
    CMSG_LOGOUT                     = 0x32,
    CMSG_SET_LOGOUT_MSG             = 0x33,
    CMSG_UPDATE_CHANNEL             = 0x34,
    SMSG_CHANNEL                    = 0x35,
    CMSG_CHANNEL_JOIN               = 0x36,
    SMSG_CHANNEL_JOIN               = 0x37,
    SMSG_CHANNEL_LEAVE              = 0x38,
    SMSG_CHANNEL_WRONG_PASSWORD     = 0x39,
    SMSG_CHANNEL_LVL_TOO_LOW        = 0x3a,
    CMSG_CHANNEL_CREATE             = 0x3b,
    SMSG_CHANNEL_CREATED            = 0x3c,
    SMSG_CHANNEL_UNABLE_TO_CREATE   = 0x3d,
    CMSG_CHANNEL_DELETE             = 0x3e,
    SMSG_CHANNEL_DELETED            = 0x3f,
    SMSG_CHANNEL_UNABLE_TO_DELETE   = 0x40,
    CMSG_CHANNEL_EDIT               = 0x41,
    SMSG_CHANNEL_EDITED             = 0x42,
    SMSG_CHANNEL_UNABLE_TO_EDIT     = 0x43,
};

#endif // SHARED_H
